import type { Transaction, BudgetLimit, CycleSummary, CategorySpending } from "@/types";

// ===== Mock Cycle Summary =====
export const mockCycleSummary: CycleSummary = {
  total_spent: 6_548_000,
  remaining_budget: 1_452_000,
  fixed_costs: 4_462_500,
  expense_costs: 2_085_500,
  savings_target: 8_000_000,
  savings_progress: 74,
  fixed_percentage: 68,
  expense_percentage: 32,
  comparison_text: "-12% vs last cycle",
};

// ===== Mock Transactions =====
export const mockTransactions: Transaction[] = [
  {
    id: "1",
    cycle_id: "cycle-1",
    category_id: "cat-lunch",
    date: "2026-01-23",
    description: "Nasi Padang",
    amount: 59_000,
    channel: "Jenius",
    cost_type: "fixed",
    is_reimbursable: false,
    is_transferred: false,
    created_at: "2026-01-23T12:00:00Z",
    category: { id: "cat-lunch", name: "Lunch", icon: "utensils", color: "orange", sort_order: 0 },
  },
  {
    id: "2",
    cycle_id: "cycle-1",
    category_id: "cat-belanja",
    date: "2026-01-22",
    description: "Indomaret Bulk",
    amount: 245_000,
    channel: "Cash",
    cost_type: "variable",
    is_reimbursable: false,
    is_transferred: false,
    created_at: "2026-01-22T10:00:00Z",
    category: { id: "cat-belanja", name: "Belanja", icon: "shopping-bag", color: "emerald", sort_order: 2 },
  },
  {
    id: "3",
    cycle_id: "cycle-1",
    category_id: "cat-transport",
    date: "2026-01-21",
    description: "Grab Ride (Work)",
    amount: 42_000,
    channel: "OVO",
    cost_type: "variable",
    is_reimbursable: false,
    is_transferred: false,
    created_at: "2026-01-21T08:00:00Z",
    category: { id: "cat-transport", name: "Transport", icon: "car", color: "blue", sort_order: 1 },
  },
  {
    id: "4",
    cycle_id: "cycle-1",
    category_id: "cat-jajan",
    date: "2026-01-21",
    description: "Starbucks Latte",
    amount: 65_000,
    channel: "BCA",
    cost_type: "variable",
    is_reimbursable: false,
    is_transferred: false,
    created_at: "2026-01-21T14:00:00Z",
    category: { id: "cat-jajan", name: "Jajan", icon: "coffee", color: "indigo", sort_order: 3 },
  },
  {
    id: "5",
    cycle_id: "cycle-1",
    category_id: "cat-self-care",
    date: "2026-01-20",
    description: "Skincare - The Ordinary",
    amount: 189_000,
    channel: "Jenius",
    cost_type: "variable",
    is_reimbursable: false,
    is_transferred: false,
    created_at: "2026-01-20T16:00:00Z",
    category: { id: "cat-self-care", name: "Self-care", icon: "heart", color: "rose", sort_order: 4 },
  },
  {
    id: "6",
    cycle_id: "cycle-1",
    category_id: "cat-lunch",
    date: "2026-01-20",
    description: "Warteg Siang",
    amount: 25_000,
    channel: "Cash",
    cost_type: "fixed",
    is_reimbursable: false,
    is_transferred: false,
    created_at: "2026-01-20T12:00:00Z",
    category: { id: "cat-lunch", name: "Lunch", icon: "utensils", color: "orange", sort_order: 0 },
  },
  {
    id: "7",
    cycle_id: "cycle-1",
    category_id: "cat-transport",
    date: "2026-01-19",
    description: "MRT Commute",
    amount: 14_000,
    channel: "BCA",
    cost_type: "fixed",
    is_reimbursable: false,
    is_transferred: false,
    created_at: "2026-01-19T07:00:00Z",
    category: { id: "cat-transport", name: "Transport", icon: "car", color: "blue", sort_order: 1 },
  },
];

// ===== Mock Budget Limits =====
export const mockBudgetLimits: BudgetLimit[] = [
  {
    id: "bl-1",
    cycle_id: "cycle-1",
    category_id: "cat-jajan",
    label: "Jajan Control",
    limit_amount: 500_000,
    spent: 391_091,
    category: { id: "cat-jajan", name: "Jajan", icon: "coffee", color: "indigo", sort_order: 3 },
  },
  {
    id: "bl-2",
    cycle_id: "cycle-1",
    category_id: "cat-transport",
    label: "Transport Bagas",
    limit_amount: 108_000,
    spent: 230_500,
    category: { id: "cat-transport", name: "Transport", icon: "car", color: "blue", sort_order: 1 },
  },
  {
    id: "bl-3",
    cycle_id: "cycle-1",
    category_id: "cat-belanja",
    label: "Domestic (Dean)",
    limit_amount: 950_000,
    spent: 581_000,
    category: { id: "cat-belanja", name: "Belanja", icon: "shopping-bag", color: "emerald", sort_order: 2 },
  },
];

// ===== Mock Category Spending =====
export const mockCategorySpending: CategorySpending[] = [
  {
    category: "Lunch",
    icon: "utensils",
    color: "#F59E0B",
    total_spent: 2_946_600,
    percentage: 45,
    tx_count: 42,
    trend: "stable",
    trend_value: "Stable",
  },
  {
    category: "Transport",
    icon: "car",
    color: "#2563EB",
    total_spent: 1_309_600,
    percentage: 20,
    tx_count: 28,
    trend: "up",
    trend_value: "+5%",
  },
  {
    category: "Belanja",
    icon: "shopping-bag",
    color: "#10B981",
    total_spent: 1_637_000,
    percentage: 25,
    tx_count: 15,
    trend: "down",
    trend_value: "-2%",
  },
  {
    category: "Jajan",
    icon: "coffee",
    color: "#6366F1",
    total_spent: 650_000,
    percentage: 7,
    tx_count: 12,
    trend: "up",
    trend_value: "+18%",
  },
  {
    category: "Self-care",
    icon: "heart",
    color: "#F43F5E",
    total_spent: 400_000,
    percentage: 3,
    tx_count: 5,
    trend: "down",
    trend_value: "Saving",
  },
];
