import {
  Utensils,
  Car,
  ShoppingBag,
  Coffee,
  Heart,
  Sunrise,
  Moon,
  Fuel,
  Shirt,
  CreditCard,
  Wifi,
  Gift,
  Home,
  ReceiptText,
  Plane,
  type LucideIcon,
} from "lucide-react";

export interface CategoryConfig {
  name: string;
  icon: LucideIcon;
  color: string;
  bgLight: string;
  bgDark: string;
  textLight: string;
  textDark: string;
  badgeBg: string;
  badgeText: string;
  hoverBg: string;
}

export const CATEGORIES: CategoryConfig[] = [
  {
    name: "Belanja",
    icon: ShoppingBag,
    color: "#10B981",
    bgLight: "bg-emerald-100",
    bgDark: "dark:bg-emerald-500/10",
    textLight: "text-emerald-600",
    textDark: "dark:text-emerald-400",
    badgeBg: "bg-emerald-100/80 dark:bg-emerald-900/30",
    badgeText: "text-emerald-700 dark:text-emerald-300",
    hoverBg: "hover:bg-emerald-500",
  },
  {
    name: "Bfast",
    icon: Sunrise,
    color: "#F59E0B",
    bgLight: "bg-amber-100",
    bgDark: "dark:bg-amber-500/10",
    textLight: "text-amber-600",
    textDark: "dark:text-amber-400",
    badgeBg: "bg-amber-100/80 dark:bg-amber-900/30",
    badgeText: "text-amber-700 dark:text-amber-300",
    hoverBg: "hover:bg-amber-500",
  },
  {
    name: "Lunch",
    icon: Utensils,
    color: "#F97316",
    bgLight: "bg-orange-100",
    bgDark: "dark:bg-orange-500/10",
    textLight: "text-orange-600",
    textDark: "dark:text-orange-400",
    badgeBg: "bg-orange-100/80 dark:bg-orange-900/30",
    badgeText: "text-orange-700 dark:text-orange-300",
    hoverBg: "hover:bg-orange-500",
  },
  {
    name: "Dinner",
    icon: Moon,
    color: "#64748B",
    bgLight: "bg-slate-100",
    bgDark: "dark:bg-slate-500/10",
    textLight: "text-slate-600",
    textDark: "dark:text-slate-400",
    badgeBg: "bg-slate-100/80 dark:bg-slate-900/30",
    badgeText: "text-slate-700 dark:text-slate-300",
    hoverBg: "hover:bg-slate-500",
  },
  {
    name: "Jajan",
    icon: Coffee,
    color: "#6366F1",
    bgLight: "bg-indigo-100",
    bgDark: "dark:bg-indigo-500/10",
    textLight: "text-indigo-600",
    textDark: "dark:text-indigo-400",
    badgeBg: "bg-indigo-100/80 dark:bg-indigo-900/30",
    badgeText: "text-indigo-700 dark:text-indigo-300",
    hoverBg: "hover:bg-indigo-500",
  },
  {
    name: "Jajan Bagas",
    icon: Coffee,
    color: "#8B5CF6",
    bgLight: "bg-purple-100",
    bgDark: "dark:bg-purple-500/10",
    textLight: "text-purple-600",
    textDark: "dark:text-purple-400",
    badgeBg: "bg-purple-100/80 dark:bg-purple-900/30",
    badgeText: "text-purple-700 dark:text-purple-300",
    hoverBg: "hover:bg-purple-500",
  },
  {
    name: "Jajan Dean",
    icon: Coffee,
    color: "#EC4899",
    bgLight: "bg-pink-100",
    bgDark: "dark:bg-pink-500/10",
    textLight: "text-pink-600",
    textDark: "dark:text-pink-400",
    badgeBg: "bg-pink-100/80 dark:bg-pink-900/30",
    badgeText: "text-pink-700 dark:text-pink-300",
    hoverBg: "hover:bg-pink-500",
  },
  {
    name: "Bensin",
    icon: Fuel,
    color: "#EF4444",
    bgLight: "bg-red-100",
    bgDark: "dark:bg-red-500/10",
    textLight: "text-red-600",
    textDark: "dark:text-red-400",
    badgeBg: "bg-red-100/80 dark:bg-red-900/30",
    badgeText: "text-red-700 dark:text-red-300",
    hoverBg: "hover:bg-red-500",
  },
  {
    name: "Transport Bagas",
    icon: Car,
    color: "#0284C7",
    bgLight: "bg-sky-100",
    bgDark: "dark:bg-sky-500/10",
    textLight: "text-sky-600",
    textDark: "dark:text-sky-400",
    badgeBg: "bg-sky-100/80 dark:bg-sky-900/30",
    badgeText: "text-sky-700 dark:text-sky-300",
    hoverBg: "hover:bg-sky-500",
  },
  {
    name: "Transport Dean",
    icon: Car,
    color: "#0D9488",
    bgLight: "bg-teal-100",
    bgDark: "dark:bg-teal-500/10",
    textLight: "text-teal-600",
    textDark: "dark:text-teal-400",
    badgeBg: "bg-teal-100/80 dark:bg-teal-900/30",
    badgeText: "text-teal-700 dark:text-teal-300",
    hoverBg: "hover:bg-teal-500",
  },
  {
    name: "Laundry",
    icon: Shirt,
    color: "#3B82F6",
    bgLight: "bg-blue-100",
    bgDark: "dark:bg-blue-500/10",
    textLight: "text-blue-600",
    textDark: "dark:text-blue-400",
    badgeBg: "bg-blue-100/80 dark:bg-blue-900/30",
    badgeText: "text-blue-700 dark:text-blue-300",
    hoverBg: "hover:bg-blue-500",
  },
  {
    name: "Cicilan",
    icon: CreditCard,
    color: "#9D174D",
    bgLight: "bg-rose-100",
    bgDark: "dark:bg-rose-500/10",
    textLight: "text-rose-600",
    textDark: "dark:text-rose-400",
    badgeBg: "bg-rose-100/80 dark:bg-rose-900/30",
    badgeText: "text-rose-700 dark:text-rose-300",
    hoverBg: "hover:bg-rose-500",
  },
  {
    name: "WIFI",
    icon: Wifi,
    color: "#14B8A6",
    bgLight: "bg-teal-100",
    bgDark: "dark:bg-teal-500/10",
    textLight: "text-teal-600",
    textDark: "dark:text-teal-400",
    badgeBg: "bg-teal-100/80 dark:bg-teal-900/30",
    badgeText: "text-teal-700 dark:text-teal-300",
    hoverBg: "hover:bg-teal-500",
  },
  {
    name: "Gift",
    icon: Gift,
    color: "#F43F5E",
    bgLight: "bg-red-100",
    bgDark: "dark:bg-red-500/10",
    textLight: "text-red-600",
    textDark: "dark:text-red-400",
    badgeBg: "bg-red-100/80 dark:bg-red-900/30",
    badgeText: "text-red-700 dark:text-red-300",
    hoverBg: "hover:bg-red-500",
  },
  {
    name: "Household",
    icon: Home,
    color: "#8B5CF6",
    bgLight: "bg-violet-100",
    bgDark: "dark:bg-violet-500/10",
    textLight: "text-violet-600",
    textDark: "dark:text-violet-400",
    badgeBg: "bg-violet-100/80 dark:bg-violet-900/30",
    badgeText: "text-violet-700 dark:text-violet-300",
    hoverBg: "hover:bg-violet-500",
  },
  {
    name: "Tagihan Rumah",
    icon: ReceiptText,
    color: "#F59E0B",
    bgLight: "bg-amber-100",
    bgDark: "dark:bg-amber-500/10",
    textLight: "text-amber-600",
    textDark: "dark:text-amber-400",
    badgeBg: "bg-amber-100/80 dark:bg-amber-900/30",
    badgeText: "text-amber-700 dark:text-amber-300",
    hoverBg: "hover:bg-amber-500",
  },
  {
    name: "Self-care",
    icon: Heart,
    color: "#F43F5E",
    bgLight: "bg-rose-100",
    bgDark: "dark:bg-rose-500/10",
    textLight: "text-rose-600",
    textDark: "dark:text-rose-400",
    badgeBg: "bg-rose-100/80 dark:bg-rose-900/30",
    badgeText: "text-rose-700 dark:text-rose-300",
    hoverBg: "hover:bg-rose-500",
  },
  {
    name: "Travel",
    icon: Plane,
    color: "#06B6D4",
    bgLight: "bg-cyan-100",
    bgDark: "dark:bg-cyan-500/10",
    textLight: "text-cyan-600",
    textDark: "dark:text-cyan-400",
    badgeBg: "bg-cyan-100/80 dark:bg-cyan-900/30",
    badgeText: "text-cyan-700 dark:text-cyan-300",
    hoverBg: "hover:bg-cyan-500",
  },
];

export const CHANNELS = [
  "BCA",
  "Mandiri",
  "Gopay",
  "Cash",
  "Jenius",
  "ShopeePay",
  "E-Money",
  "DANA",
  "OVO",
  "Credit Card",
] as const;

export type Channel = (typeof CHANNELS)[number];

export function getCategoryConfig(name: string): CategoryConfig | undefined {
  return CATEGORIES.find(
    (c) => c.name.toLowerCase() === name.toLowerCase()
  );
}

// Channel badge styles
export const CHANNEL_STYLES: Record<string, { bg: string; text: string }> = {
  BCA: {
    bg: "bg-blue-100/80 dark:bg-blue-900/40",
    text: "text-blue-700 dark:text-blue-300",
  },
  Mandiri: {
    bg: "bg-amber-100/80 dark:bg-amber-900/40",
    text: "text-amber-700 dark:text-amber-300",
  },
  Gopay: {
    bg: "bg-sky-100/80 dark:bg-sky-900/40",
    text: "text-sky-700 dark:text-sky-300",
  },
  Cash: {
    bg: "bg-emerald-100/80 dark:bg-emerald-900/40",
    text: "text-emerald-700 dark:text-emerald-300",
  },
  Jenius: {
    bg: "bg-cyan-100/80 dark:bg-cyan-900/40",
    text: "text-cyan-700 dark:text-cyan-300",
  },
  ShopeePay: {
    bg: "bg-orange-100/80 dark:bg-orange-900/40",
    text: "text-orange-700 dark:text-orange-300",
  },
  "E-Money": {
    bg: "bg-slate-200/80 dark:bg-slate-800/80",
    text: "text-slate-700 dark:text-slate-300",
  },
  DANA: {
    bg: "bg-indigo-100/80 dark:bg-indigo-900/40",
    text: "text-indigo-700 dark:text-indigo-300",
  },
  OVO: {
    bg: "bg-purple-100/80 dark:bg-purple-900/40",
    text: "text-purple-700 dark:text-purple-300",
  },
  "Credit Card": {
    bg: "bg-zinc-200/80 dark:bg-zinc-800/80",
    text: "text-zinc-700 dark:text-zinc-300",
  },
};
